image: maven:3.5.4-jdk-8-alpine

variables:
  MAVEN_OPTS: "-Dmaven.repo.local=$CI_PROJECT_DIR/.m2"
  MAVEN_CLI_OPTS: "--settings settings.xml --batch-mode"

cache:
  paths:
    - .m2/
  key: ${CI_COMMIT_REF_SLUG}


stages:
  - build
  - trigger
  - test

build_dev:
  stage: build
  script:
    - "mvn $MAVEN_CLI_OPTS $MAVEN_OPTS clean install"
  only:
    - dev

build_branches:
  stage: build
  script:
    - "mvn $MAVEN_CLI_OPTS $MAVEN_OPTS clean install"
  except:
    - dev