# (c) https://github.com/MontiCore/monticore
image: registry.git.rwth-aachen.de/monticore/container-registry/gradle:7.4.2-jdk11

variables:
  GRADLE_OPTS: "-Dorg.gradle.daemon=false"


before_script:
  - export GRADLE_USER_HOME=`pwd`/.gradle

stages:
  - build
  - test
  - deploy


build:
  stage: build
  script:
    - "gradle assemble --refresh-dependencies $GRADLE_OPTS $ARGS1"
  artifacts:
    paths:
      - "."
    expire_in: 1 week

test:
  stage: test
  dependencies:
    - build
  script:
    - "gradle check $GRADLE_OPTS $ARGS2"

deploy:
  stage: deploy
  dependencies:
    - build
  script:
    - "gradle publish $GRADLE_OPTS $ARGS3 -PmavenPassword=$password -PmavenUser=$username"
  only:
    - dev