mavenUser=${user}
mavenPassword=${password}
repo=https://nexus.se.rwth-aachen.de/content/groups/public

useLocalRepo=false

org.gradle.caching=true
org.gradle.welcome=never
org.gradle.jvmargs=-Xms3072m -Xss16m -Dfile.encoding=UTF-8

version=7.9.0-SNAPSHOT

# dependency versions
mc_version=7.9.0-SNAPSHOT
emf_version=2.15.0
shadow_plugin_version=8.3.9
guava_version=31.1-jre
junit_version=6.1.0
google_java_format_version=0.9
spoon_core_version=11.3.0
commons_lang3_version=3.9