description = "MontiCore: Java DSL"

def grammarsDir = "src/main/grammars"

configurations {
    corpus {
        canBeConsumed = false
        canBeResolved = true

        transitive = false

        resolutionStrategy.dependencySubstitution.all {
            artifactSelection {
                selectArtifact("jar", "jar", "sources")
            }
        }
    }
}


tasks.register('extractCorpus') {
    dependsOn(configurations.corpus)

    def destinationDir = layout.buildDirectory.dir("corpus")

    inputs.files(provider { configurations.corpus })
    outputs.dir(destinationDir)
    outputs.cacheIf { true }

    doLast {
        copy {
            into(destinationDir)

            includeEmptyDirs = false
            include("**/*java")

            configurations.corpus.each { file ->
                into(file.name.substring(0, file.name.lastIndexOf("."))) {
                    from(zipTree(file))
                }
            }
        }
    }
}

tasks.withType(Test).configureEach {
    dependsOn(extractCorpus)
}

dependencies {
    implementation "de.monticore.lang:cd4analysis:$mc_version"
    implementation "de.monticore:class2mc:$mc_version"

    grammar "de.monticore:monticore-grammar:$mc_version"

    testImplementation testFixtures("de.monticore:monticore-grammar:$mc_version")
    testImplementation "org.junit.jupiter:junit-jupiter-api:$junit_version"
    testImplementation "org.junit.jupiter:junit-jupiter-params:$junit_version"
    testRuntimeOnly "org.junit.jupiter:junit-jupiter-engine:$junit_version"

    corpus(corpusLibs.guava)
    corpus(corpusLibs.monticore.runtime)
    // TODO: fix parser for Java 17 and enable
    //corpus(corpusLibs.quitte)
}