import com.github.sherter.googlejavaformatgradleplugin.VerifyGoogleJavaFormat

plugins {
    id 'java'
    id 'java-gradle-plugin'
    id 'maven-publish'

    id "de.monticore.generator" version "$mc_version"
    id "com.gradleup.shadow" version "$shadow_plugin_version"
    id "com.github.sherter.google-java-format" version "$google_java_format_version"  // Task "verifyGoogleJavaFormat" and "googleJavaFormat"
}

dependencies {
    implementation project(":javaDSL")
    implementation "de.se_rwth.commons:se-commons-logging:$mc_version"
    implementation "de.monticore:monticore-runtime:$mc_version"
    implementation "de.monticore:monticore-grammar:$mc_version"
    implementation "de.monticore:class2mc:$mc_version"
    implementation "de.monticore.lang:cd4analysis:$mc_version"
    implementation "de.monticore.lang:od:$mc_version"
    implementation "com.google.guava:guava:$guava_version"
    implementation "fr.inria.gforge.spoon:spoon-core:$spoon_core_version"

    implementation "org.apache.commons:commons-lang3:$commons_lang3_version"

    implementation "de.monticore.lang:cd4analysis:$mc_version:cddiff"
    implementation "de.monticore.lang:cd4analysis:$mc_version:tool"

    implementation "org.junit.jupiter:junit-jupiter-api:$junit_version"
    testImplementation "org.junit.jupiter:junit-jupiter-params:$junit_version"
    testImplementation "org.junit.jupiter:junit-jupiter-engine:$junit_version"
    testRuntimeOnly "org.junit.platform:junit-platform-launcher:$junit_version"

    grammar("de.monticore.lang:cd4analysis:$mc_version")
    grammar("de.monticore:monticore-grammar:$mc_version")
}

shadowJar { // all in one jar
    manifest {
        attributes "Main-Class": "de.monticore.codeAdaption.CodeAdapterTool"
    }
    archiveClassifier = 'cli'
    archiveFileName = "CodeAdapter.jar"
    zip64 = true
//        minimize()
    duplicatesStrategy = DuplicatesStrategy.INCLUDE
}

test {
    useJUnitPlatform()
}

group = 'refCodeAdaptation'

description = 'CoEvolution'
layout.buildDirectory = layout.projectDirectory.dir("target")


googleJavaFormat {
    exclude '**/target/**'
    exclude '**/test/resources/**'
    exclude '***/test/java/model/reference/hwc/Application'
}

verifyGoogleJavaFormat{
    ignoreFailures = true
    exclude "**"
}  // do not check format in "build"

tasks.register('checkfmt', VerifyGoogleJavaFormat) {}

tasks.register('fmt') {
    dependsOn tasks.named("googleJavaFormat")
}