description = "MontiCore: Java DSL EMF"

def srcMainDir = "$buildDir/copied-sources/main"
def srcTestDir = "$buildDir/copied-sources/test"

def grammarsDir = "${project(":javaDSL").projectDir}/src/main/grammars"

tasks.register('copyMainSources', Copy) {
    destinationDir = file srcMainDir
    from "${project(':javaDSL').projectDir}/src/main"
}

tasks.register('copyTestSources', Copy) {
    destinationDir = file srcTestDir
    from "${project(':javaDSL').projectDir}/src/main"
}

generateMCGrammars {
    dependsOn(copyMainSources, copyTestSources)
    script = "de/monticore/monticore_emf.groovy"
}

dependencies {
    implementation "de.monticore.lang:cd4analysis:$mc_version"

    implementation "org.eclipse.emf:org.eclipse.emf.common:$emf_version"
    implementation "org.eclipse.emf:org.eclipse.emf.ecore:$emf_version"
    implementation "org.eclipse.emf:org.eclipse.emf.ecore.xmi:$emf_version"

    grammar "de.monticore:monticore-grammar-emf:$mc_version"
    implementation "de.monticore:monticore-runtime-emf:$mc_version"

    testImplementation "org.junit.jupiter:junit-jupiter-api:$junit_version"
    testImplementation "org.junit.jupiter:junit-jupiter-params:$junit_version"
    testImplementation "org.junit.jupiter:junit-jupiter-engine:$junit_version"
    testRuntimeOnly "org.junit.platform:junit-platform-launcher:$junit_version"
}